name: DesignPatternCI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # 矩阵配置
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: windows-build
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=release
        nmake
        ctest -C Release -V -j
    - name: unix-build
      if: matrix.os != 'windows-latest'
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=release
        make -j4
        ctest -j 2 -V 
